#!/usr/bin/env node
const path = require('path');
const fsp = require('fs/promises');
const pkg = require('../package.json');

const [user, repo] = pkg.repository.url
  .replace('git+https://github.com/', '')
  .replace('.git', '')
  .split('/');

const docsCleanup = async () => {
  const docs = path.resolve(__dirname, '../docs');
  const files = (await fsp.readdir(docs))
    .filter((file) => file.endsWith('.html'))
    .map((file) => path.resolve(docs, file));
  const promises = files.map(async (file) => {
    const content = await fsp.readFile(file, 'utf-8');
    const newContent = content
      .replace(/\.\/docs\//g, './')
      .replace(
        /\.\/LICENSE/g,
        `https://github.com/${user}/${repo}/blob/main/LICENSE`
      );
    await fsp.writeFile(file, newContent);
  });
  await Promise.all(promises);
};

docsCleanup().catch(console.error);
