#!/usr/bin/env bash
set -e

# functions
function trash {
    local src=$1
    src_basename=$(basename "$src")
    now=$(date +%s)

    if ! [ -e "$src" ]; then
      echo "$src not found"
      return
    fi

    # check for trash, just in case
    if [ -d  "$HOME/.Trash" ]; then
      mv "$src" "$HOME/.Trash/${src_basename}_${now}_${RANDOM}"
    else
      rm -rf "$src"
    fi
}

# run setup script
.bin/scripts/setup

# delete .bin/scripts and setup dir
trash .bin/scripts
trash .bin/setup
npm pkg delete scripts.setup

# install depenendenies
npm ci
